### ISSUE TITLE
Is there a training part to this code

### ISSUE THREAD

**Issue by wtx9527** [shaohua-pan/RobustCap#12]
If I want to train my own network, in which file should I make changes

**Comment by shaohua-pan** [comment]
I will share the training code. Maybe this will take few days.

**Comment by wtx9527** [comment]
Hi, I want to visualize the 3DPW data, do I need to re-preprocess the 3DPW in the AIST section in the process, or by some other means

**Comment by wtx9527** [comment]
Hi, it's been many days, please upload the training part while you rest, thank you very much

**Comment by shaohua-pan** [comment]
I have updated the code.
