### ISSUE TITLE
Questions about the acceleration

### ISSUE THREAD

**Issue by ElectronicElephant** [shaohua-pan/RobustCap#14]
Hi,

Thanks for sharing the code of the awesome project!

I have some questions about the acceleration from the IMUs.

First, what is the unit of the acceleration? Is it SI (m/s^2) or G (g)?

Second, is the gravity cancelled out from the acceleration? I suppose the synthetic acc generated from the AIST++ dataset does not consider the gravity, but the readings from IMUs contain the gravity.

Thanks.

**Comment by shaohua-pan** [comment]
The unit of the acceleration is m/s^2. The gravity is canceled from the IMU readings.
