### ISSUE TITLE
tpose_calibration中 RSC矩阵的问题

### ISSUE THREAD

**Issue by degts** [shaohua-pan/RobustCap#19]
https://github.com/shaohua-pan/RobustCap/blob/360f8aeca8bf62c766b86bec57163f0405f13c61/live_demo_sync.py#L85C13-   请问RSC代表sensor坐标系到camera坐标系的变换矩阵吗？代码是直接赋值，这个依据是什么呢？

**Comment by shaohua-pan** [comment]
对，是S和C之间的旋转变换矩阵，已知相机坐标系三个轴和传感器坐标系三个轴，把两者放到一起，根据不同坐标轴对应关系，可以直接写出这个旋转矩阵

**Comment by degts** [comment]
感谢您的回复！还想请问在获取数据的时候，对相机的和人的相对位置有要求吗？

**Comment by shaohua-pan** [comment]
只需要标定一次就可以了，后边需要固定相机，其他没有要求了

**Comment by degts** [comment]
好的明白，感谢回复！
