### ISSUE TITLE
请问imus_addr这个参数

### ISSUE THREAD

**Issue by zhaohuazhenshuai** [shaohua-pan/RobustCap#6]
请问这个参数代表什么意思呢？指的imu设备地址吗？还是?还有Imu数据格式能否开源？

**Comment by shaohua-pan** [comment]
对，IMU蓝牙的地址

**Comment by zhaohuazhenshuai** [comment]
您好，我还有一个疑问，就是live_demo这个里面需要连接Unity3d吗，在哪个部分是连接unity3d呢？谢谢您的回复

**Comment by shaohua-pan** [comment]
有的，live_server.py会把Motion通过socket发给Unity，Unity渲染就可以了

**Comment by zhaohuazhenshuai** [comment]
可否在了解一下，为什么unity3d那部分我连不上呢，我该如何处理呢，连接的地址和端口一致显示无响应，这是什么问题呢
感谢您可以回答我

**Comment by shaohua-pan** [comment]
这个可能还是得你自己排查一下

**Comment by shaohua-pan** [comment]
已经上传了Live Demo的代码，可以试一下。
