### ISSUE TITLE
请教关于unity3d问题

### ISSUE THREAD

**Issue by zhaohuazhenshuai** [shaohua-pan/RobustCap#7]
您好，我目前有个问题，就是在unity3d渲染，我在跑live_server这个时候，显示无法连接unity3d，是否是缺少unity客户端代码，还是我做的有问题，拜托，请您回复一下，谢谢

**Comment by zhaohuazhenshuai** [comment]
如果可以的话，可以加您的微信交流一下吗，wzh102598

**Comment by shaohua-pan** [comment]
Live 的代码unity部分我还没有上传，需要写一下接收数据并渲染的代码，可以参考一下 https://github.com/Xinyu-Yi/TransPose 提供的Unity scene.

**Comment by shaohua-pan** [comment]
已经更新了live demo部分的代码。
